# ==============================================================================
# DH Odoo Audit Engine: REVISED & OPTIMIZED postgresql.conf
# Target Spesifikasi: 13.7 GB RAM | Media Penyimpanan: SSD/NVMe
# ==============================================================================

# Memory Optimization
shared_buffers = 3GB
effective_cache_size = 10GB
maintenance_work_mem = 1402MB
work_mem = 16MB

# Query Planner & Storage Tuning (Penting untuk SSD)
random_page_cost = 1.1
effective_io_concurrency = 200

# Write-Ahead Logging & Checkpoints
wal_buffers = 16MB
min_wal_size = 1GB
max_wal_size = 4GB
checkpoint_completion_target = 0.9
