# Sample unoptimized nginx config for Odoo
upstream odoo {
    server 127.0.0.1:8069;
}

server {
    listen 80;
    server_name erp.example.com;

    proxy_read_timeout 60s;
    proxy_connect_timeout 60s;
    client_max_body_size 1m;

    location / {
        proxy_pass http://odoo;
        proxy_set_header Host $host;
        # Missing X-Forwarded-Host & Proto
        # Missing Longpolling 8072 split
    }
}
