# ==============================================================================
# DH Odoo Audit Engine: REVISED Linux Kernel sysctl.conf
# Mencegah OS memindahkan RAM aktif Odoo/PostgreSQL ke swap disk
# ==============================================================================

# Turunkan kecenderungan swap dari default 60 menjadi 10
vm.swappiness = 10

# Batas file descriptors untuk banyak koneksi worker Odoo
fs.file-max = 2097152
